version: '3'

services:
  backend:
    image: toynetreact_backend:latest 
    networks:
      - reclass_network
    ports:
      - "8000:8000"
    environment:
      - SECRET_KEY="iamnotaverysecretkey"

  frontend:
    image: toynetreact_frontend:latest 
    ports:
      - "3000:80"
    networks:
      - reclass_network
    depends_on:
      - backend
    environment:
      - SERVER_URI="http://backend:8000"

networks:
  reclass_network:
