#!/usr/bin/env bash

sudo docker load -i ./toynet-django.tar > /dev/null 2>&1
sudo docker load -i ./toynet-react.tar > /dev/null 2>&1

sudo docker-compose -f ./docker-compose.yml up -d --build > /dev/null 2>&1

firefox localhost:3000 > /dev/null 2>&1